services:
  ollama:
    container_name: ollama_container
    build:
      context: .
      dockerfile: Dockerfile-LLM
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
