# Importing necessary classes
from llm.src.conf.Configurations import logger, default_prompt
from langchain_core.prompts import PromptTemplate
from langchain_community.llms import LlamaCpp
from llm.src.utilities.Llama2Pipeline import Llama2Pipeline


def llama2_chat_ggu_question_answering(context: str, questions: list[str]):
    """
    Perform question answering using the Llama2ChatGGUF model via LangChain's LlamaCpp integration.
    :param context: The context in which to answer the question.
    :param questions: List of questions to answer.
    :return: The answers generated by the Llama2ChatGGUF model.
    """

    logger.info("Received a request to perform question answering using Llama2ChatGGUF model")

    # Load the Llama2 GGUF model using LangChain's LlamaCpp
    logger.info("Loading Llama2 GGUF model")
    llm = Llama2Pipeline().get_llm_model()

    # Enforcing that the model should strictly answer from context or say "I don't know"
    system_msg = f"{default_prompt}"

    # Format the prompt with context and the current question
    user_msg = f"CONTEXT:{context} \nQUESTION:{questions}"

    logger.info(f"Generating response for question: {questions}")

    # Generate the response using LangChain's LlamaCpp model
    response = llm.invoke(
        input=f"{system_msg}\n{user_msg}"
    )

    return response

if __name__ == "__main__":
    # Sample context and question
    sample_context = "The capital of France is Paris. The Eiffel Tower is located in Paris."
    sample_questions = ["What is the capital of France?", "Where is the Eiffel Tower located?", "What is the capital of Germany?"]

    # Perform question answering using the Llama2ChatGGUF model
    res = llama2_chat_ggu_question_answering(sample_context, sample_questions)

    # Print the response
    print(res)
