# Importing necessary classes
from llm.src.utilities.OllamaPipeline import OllamaPipeline
from llm.src.conf.Configurations import logger
from fastapi import HTTPException
from llm.src.conf.Prompts import default_prompt1
import PyPDF2



def qa_with_ollama(context: str, questions: list[str]):
    """
    Perform question answering using the Ollama model
    :param context: The context in which to answer the question.
    :param questions: The questions to answer.
    :return: The answer generated by the Ollama model.
    """

    # Load the Ollama model
    model = OllamaPipeline().get_model()
    logger.info("Model initialized.")

    examples = """
        Example format:
        Q: What is the title of the document?
        A: Sample Document Title

        Q: Who is the authorizing agent of the document?
        A: Dr. John Doe.

        Q. Does the document has CDRL number?
        A. Answer not found in the information provided.

        Please respond in a similar format.
        """

    system_prompt = f"{default_prompt1} \n\n {examples}"

    # Define the user prompt with the question and context
    user_prompt = f"The question is: {questions} \n\n The information provided is: {context}"

    prompt = f"""<|begin_of_text|><|start_header_id|>system<|end_header_id|>

    {system_prompt}<|eot_id|><|start_header_id|>user<|end_header_id|>

    {user_prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>"""

    # Invoke the model with the chat structure
    try:
        # Directly invoke the model with the formatted prompt
        logger.info("invoking the model with input message")
        response = model.invoke(input=prompt)
        logger.info("response received from the model")
        logger.info(f"response: {response}")

        return response
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An error occurred during invocation: {e}")


if __name__ == "__main__":

    pdf_text = ''
    with open(r"C:\Docs\sample.pdf", 'rb') as pdf_file:
        pdf_reader = PyPDF2.PdfReader(pdf_file)
        pdf_text += str(pdf_reader.metadata)
        for page_num in range(min(1, len(pdf_reader.pages))):
            page = pdf_reader.pages[page_num]
            pdf_text += page.extract_text()

    QUESTIONS = ["What is the title of the document?", "What is the creation date of the document?",
                 "What is the version of the document?", "Does the document has CDRL number?",
                 "Who is the authorizing agent of the document?"]

    QUESTION = ["What is the title of the document?"]

    text="New Delhi is the capital of India. It is located in Asia. The population of India is 1.4 billion."
    question = ["What is the capital of India?"]
    res = qa_with_ollama(text, question)

    print(res)