# Importing necessary classes
from llm.src.utilities.OllamaPipeline import OllamaPipeline
from llm.src.conf.Configurations import logger
from fastapi import HTTPException
from llm.src.conf.Prompts import default_prompt1

def qa_with_ollama(context: str, questions: list[str]):
    """
    Perform question answering using the Ollama model
    :param context: The context in which to answer the question.
    :param question: The question to answer.
    :return: The answer generated by the Ollama model.
    """

    # Load the Ollama model
    model = OllamaPipeline().get_model()
    logger.info("Model initialized.")

    responses = []

    for question in questions:
        # Define messages in the chat format with "system," "user," and "content"
        message = [
            {"role": "system",
             "content": default_prompt1},
            {"role": "user", "content": question},
            {"role": "assistant",
             "content": context}]

        # Invoke the model with the chat structure
        try:
            # Directly invoke the model with the formatted prompt
            logger.info("invoking the model with input message")
            response = model.invoke(input=message)
            logger.info("response received from the model")

            responses.append(response)
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"An error occurred during invocation: {e}")

    return responses



if __name__ == "__main__":

    sample_context = "Artificial Intelligence (AI) refers to the simulation of human intelligence in machines designed to think and learn like humans. AI systems can perform tasks such as image recognition, natural language processing, decision-making, and autonomous driving. Machine learning (ML) is a subset of AI that allows computers to learn from data and improve their performance without being explicitly programmed. Deep learning, a type of machine learning, uses neural networks with many layers to analyze large datasets. AI has applications across various industries, including healthcare, finance, and entertainment, and continues to evolve as computing power increases"

    Questions = [
        "What is the difference between AI and machine learning?",
        "How does deep learning work in artificial intelligence?",
        "Who is the founder of AI?",  # Out of context
        "What are the ethical concerns surrounding the use of AI in surveillance?"  # Out of context
    ]

    res = qa_with_ollama(sample_context, Questions)

    for answer, question in zip(res, Questions):
        print(f"Question: {question}\nAnswer: {answer}\n")


